#!/bin/bash
# Control services for system based on Systemd inside chroot and SysVinit outside chroot
# https://github.com/smaknsk/servicectl
#

# Path contents symlink on systemd units files
SERVICECTL_ENABLED_PATH=="/etc/init.d-chroot/"

action="start"
if [[ -n $1 ]]; then
    action=$1
fi

servicectl $action $(dir $SERVICECTL_ENABLED_PATH)
